const WINDOW_STORAGE_EVENT = 'storage';
const GET_SESSION_STORAGE_KEY = '_getSessionStorage';
const SET_SESSION_STORAGE_KEY = '_setSessionStorage';
const CLEAR_SESSION_STORAGE_KEY = '_clearSessionStorage';
const DELETE_SESSION_STORAGE_KEY = '_deleteSessionStorage';
const ADD_TO_SESSION_STORAGE_KEY = '_addToSessionStorage';
const SESSION_STORAGE_ID = '_sessionStorageId';

export {
    WINDOW_STORAGE_EVENT,
    GET_SESSION_STORAGE_KEY,
    SET_SESSION_STORAGE_KEY,
    CLEAR_SESSION_STORAGE_KEY,
    DELETE_SESSION_STORAGE_KEY,
    ADD_TO_SESSION_STORAGE_KEY,
    SESSION_STORAGE_ID
};